ymc_how_to_acl:
    resource: "@YmcHowToAclBundle/Resources/config/routing.yml"
    prefix:   /

ymc_how_to_common:
    resource: "@YmcHowToCommonBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
